### ISSUE TITLE
latex cannot find listings-rust.sty file

### ISSUE THREAD

**Issue by ZZZping** [denki/listings-rust#4]
I place the listings-rust.sty file in the folder listings, but latex cannot find the file

**Comment by jvdd** [comment]
How did you overcome this @ZZZping? 

I have exactly the same issue - it works like a charm in overleaf, but when submitting to elsevier (with the `listings-rust.sty`) I get the following error: 

```
LaTeX Error: File `listings-rust.sty' not found.
```
